D:\Users\Jalouke\Documents\GitHub\Oresat\oresat-structure\Rev v0.2\Module_Placeholder_PCB_withRF-Static 2
D:\Users\Jalouke\Documents\GitHub\Oresat\oresat-structure\Rev v0.2\Module_Placeholder_PCB_withRF-Static 2
D:\Users\Jalouke\Documents\GitHub\Oresat\oresat-structure\Rev v0.2\Module_Placeholder_PCB_withRF-Static 2
D:\Users\Jalouke\Documents\GitHub\Oresat\oresat-structure\Rev v0.2\Module_Placeholder_PCB_withRF-Static 2
D:\Users\Jalouke\Documents\GitHub\Oresat\oresat-structure\Rev v0.2\Module_Placeholder_PCB_withRF-Static 2
D:\Users\Jalouke\Documents\GitHub\Oresat\oresat-structure\Rev v0.2\Module_Placeholder_PCB_withRF-Static 2
